version: "3.3"
services:
  server:
    build: .
    expose:
      - "3000"
    volumes:
      - .:/code
    command: "nodemon src/index.js"
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "4000:4000"
